[package]
name = "stof-cli"
version = "0.4.9"
edition = "2021"
authors = ["CJ Cummings <cj@formata.io>"]
description = "The official CLI for Stof. Stof is a unified data interface and interchange format for creating, sharing, and manipulating data. Stof removes the fragile and cumbersome parts of combining and using data in applications."
license = "Apache-2.0"
repository = "https://github.com/dev-formata-io/stof-cli"
homepage = "https://docs.stof.dev"

[[bin]]
name = "stof"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
colored = "3.0.0"
stof = "0.3.5"
stof-github = "0.1.4"
stof-http = "0.2.3"
