[package]
name = "stof-cli"
version = "0.12.0"
edition = "2024"
authors = ["CJ Cummings <cj@formata.io>"]
description = "Command-line tool for Stof: run, test, document, and package portable, sandboxed logic inside data."
license = "Apache-2.0"
repository = "https://github.com/dev-formata-io/stof-cli"
homepage = "https://stof.dev"
keywords = ["stof", "cli", "sandbox", "scripting", "json"]
categories = ["development-tools", "command-line-utilities"]

[[bin]]
name = "stof"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
colored = "3.0.0"
colog = "1.3.0"
env_logger = "0.11.8"
log = "0.4.28"
stof = { version = "0.10.1", path = "../stof", features = ["full"] } # path for local builds (ignored when publishing)
