[package]
name = "stof-cli"
version = "0.4.6"
edition = "2021"
authors = ["CJ Cummings <cj@formata.io>"]
description = "The official CLI for Stof. Stof is efficient, governable, and accessible data that is much simpler to use, offering fine-grained control and sandboxed manipulation between computer systems without the need for additional application code, servers, and dependencies."
license = "Apache-2.0"
repository = "https://github.com/dev-formata-io/stof-cli"
homepage = "https://docs.stof.dev"

[[bin]]
name = "stof"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
colored = "3.0.0"
stof = "0.3.2"
stof-github = "0.1.4"
stof-http = "0.2.3"
